# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 23:40
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField(default=10)),
                ('unit', models.PositiveIntegerField(choices=[(30, '30 min'), (60, '1 hour'), (120, '2 hours')], default=60)),
            ],
        ),
        migrations.CreateModel(
            name='AddonsEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Addon')),
            ],
        ),
        migrations.CreateModel(
            name='AddonsStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addons', models.ManyToManyField(to='booking.AddonsEntity')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('adults', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('addons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.AddonsStack')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('sex', models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=True)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, max_length=32)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DateInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RentPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.DateInterval')),
            ],
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price_per_night', models.IntegerField(default=10)),
                ('rent_periods', models.ManyToManyField(blank=True, to='booking.RentPeriod')),
            ],
        ),
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('finish_time', models.TimeField(default=datetime.time(0, 0))),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.Client'),
        ),
        migrations.AddField(
            model_name='booking',
            name='period',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.RentPeriod'),
        ),
        migrations.AddField(
            model_name='booking',
            name='suites',
            field=models.ManyToManyField(to='booking.Suite'),
        ),
        migrations.AddField(
            model_name='addonsentity',
            name='interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.TimeInterval'),
        ),
    ]
