# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BusyDateRangeOfSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SuiteEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='busydaterangeofsuite',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.SuiteEntity'),
        ),
        migrations.AddField(
            model_name='booking',
            name='suite',
            field=models.ManyToManyField(to='booking.SuiteEntity'),
        ),
    ]
